export const LETTER_WIDTH = 9.61;
export const LETTER_HEIGHT = 21;
export const LEFT_AND_RIGHT_PADDING = 16;
export const TOP_AND_BOTTOM_PADDING = 20;
export const MIN_BLOCK_WIDTH = 130 + LEFT_AND_RIGHT_PADDING;
export const MAX_BLOCK_WIDTH = 330 + LEFT_AND_RIGHT_PADDING;